### ISSUE TITLE
Initial work on Setup application

### ISSUE THREAD

**Issue by Ashwin-MJ** [ESE-Peasy/NarrateMyWay#31]
# Goal

A skeleton app should be setup

# Plan

1. Create a new app using Expo
1. Setup a basic structure which meets the requirements of this app

**Comment by miklasr** [comment]
Very basic version of setup app is working. The user is able to generate a code based on three dropdown menus. Currently all boxes need to be selected for a code to be generated and there are still a few bugs. The current version works as a very minimum working example.

This is all on the new NMW beacon setup repo so this issue can now be closed with any work continuing on the other repo.
