### ISSUE TITLE
Research accessibilty options

### ISSUE THREAD

**Issue by miklasr** [ESE-Peasy/NarrateMyWay#6]
Research various methods for improving accessibility of apps. Currently we have identified descriptions that can be set for widgets, similar to `alt` text in HTML. Research if other things in this vein also exist.

**Comment by Ashwin-MJ** [comment]
React Native have some guidance for how to use accessibility options during development [here](https://reactnative.dev/docs/accessibility). To summarise, there are some properties which we can set which make use of VoiceOver (iOS) and TalkBack (Android) to provide audio feedback to users. We should ensure we always set the `accessibilityLabel` for components during development to make use of this - might be worth adding to the pull request template to enforce this

**Comment by Ashwin-MJ** [comment]
Aside from adding accessibility options within the code itself, there are other things which we should consider too ([this](https://www.invisionapp.com/inside-design/mobile-design-visually-impaired/) and [this](https://willowtreeapps.com/ideas/how-to-design-accessible-mobile-experiences-for-the-blind) seem to be good references):
1. Font size - ideally we should be able to dynamically modify our font size based on the OS settings, but if this is not possible we should offer a few different font options which can be chosen
2. Colour scheme - we need to be careful to consider users who may be colour blind and therefore we need to think about what colour scheme to use to best aid accessibility
3. Ensure buttons and loading states also make use of screen reading tools
4. Use descriptive language
5. App hierarchy - our app shouldn't be too complicated anyway, but we need to be ensure navigating between pages is as easy and obvious as possible
